### ISSUE TITLE
Automated testing strategy for RN Tester app

### ISSUE THREAD

**Issue by jevakallio** [MLH-Fellowship/react-native#11]
## Goals

To understand the following:

- [x] What is the purpose of automated testing for RNTester
- [x] What tools will we use to test RNTester
- [x] What type of test coverage will best serve us (smoke tests? cover every edge case? else?)
...

## Outcome

- Guidance and documentation on how to 
  - Write tests for RNTester screens
  - Setup testing tools for iOS and Android
  - ?

**Comment by anku255** [comment]
# What is the purpose of automated testing for RNTester

`react-native` has a lot of components and APIs. The goal of RNTester app is to test the working of these components and APIs whenever a change is made to source of `react-native`.


## Some questions regarding expectations

- Smoke test (Just making sure component renders) vs covering out every cases
- Answer: 

  - What about smoke tests for components that are difficult to test. For example - `ScrollView`. Would it be helpful to just make sure it renders properly?
  - Answer: 

- How to go about testing components which are not interactive. For example - `ActivityIndicator`. 
- Answer: 

- How to go about testing APIs which do not have any visual part to it. For example - `Vibration`
- Answer: 



### Unit Testing and Integration Tests

Does Unit Testing or Integration testings bring any value for RNTester app? Specially testing out the rendering of components using something like `react-native-testing-library`? 

 - Pros 
   - Tests are easier and faster to run.

 - Cons
   - If we are going to write and run `e2e` tests then these become redundant
   - These tests do not run on actual device environments and don't bring a lot of confidence.


Answer:
### Choice of library

- For `e2e` tests Detox stills seems like the best choice. 
- There is `Appium` which can be used to do `e2e` on android but it is not cross platform like Detox. If we do face major issues with Detox on android then we can look into it more.

TODO: Figure out if we can write platform independent tests using Detox.


### Structure of tests directory

There are some tests which are platform specific. We need to find a way to categorize these tests. For example, there is no `Alert Prompt` in android but it exists in iOS. So, we need to make sure we run these tests only on iOS.

- First way of doing this could be created three folders inside of `e2e/__tests__` 
  - `common`, `ios`, and ,`android`.

- The other way of doing this is to specify it in each filename. For example - 
  - `Component-ios.js` for ios specific.
  - `Component-android.js` for android specific.
  - `Component-both.js` or `Component-common.js` for tests that are common for both platforms.

- We can modify the test runner script accordingly to pick only required files to tests.


Answer:

**Comment by jevakallio** [comment]
Regarding the structure of tests directory, React Native already has support for [platform-specific extensions](https://reactnative.dev/docs/platform-specific-code#platform-specific-extensions) using `file.{platform}.js` format. I'm not sure if Detox supports this out of the box, but we should try that first, since it will be familiar for React Native developers.

The way it works is that it picks up the most specific matching name, so if we have both `Component.js` and `Component.android.js`, on Android it will pick up the latter, but on iOS (and all other platforms) it'll use the former, because a more specific file isn't available.

This means that if we do have common tests for both platforms, we can't use `Component.js` for that as it will get shadowed by the platform-specific extension. For that, I like `Component-common.js`, but @rickhanlonii can verify. 

I don't like separate folders, as tests that are ran together should live together in the file system structure so they're easy to navigate between and discover.

**Comment by jevakallio** [comment]
Regarding choice of library, Detox seems like the best option if we can get rid of the flakiness. Let's discuss this with Ricky.

**Comment by jevakallio** [comment]
> [Unit testing RNTester] would not be useful for as it only exercises JS context and we want to test things in the native environment.

Agreed. End-to-end or bust 😅

**Comment by jevakallio** [comment]
> What about smoke tests for components that are difficult to test. For example - ScrollView. Would it be helpful to just make sure it renders properly?

@rickhanlonii should weigh in on this.

> How to go about testing components which are not interactive. For example - ActivityIndicator.

If we decide that smoke tests, aka. "check that it renders" tests are valuable, these would be a good candidate for that type of test.

> How to go about testing APIs which do not have any visual part to it. For example - Vibration

Again, @rickhanlonii can help us decide whether these are valuable, but I think there might be value in writing tests that call the native API methods and check that they return the correct values. See Expo's test suite as an example of this type of test:
https://github.com/expo/expo/tree/master/apps/test-suite/tests
