### ISSUE TITLE
Implement new FlatList Screen

### ISSUE THREAD

**Issue by sansyrox** [MLH-Fellowship/react-native#112]
## UseCases
- [x] Horizontal Mode
- [x] Pull To Refresh
- [ ] Separator Support
    - Currently present but not optional in the demo
- [x] Multiple Column Support
   - ToDo
- [x] Header Support
    - Currently present but not optional in the demo
- [x] Footer Support
    - Currently present but not optional in the demo
- [x] ScrollToIndex Support
- [ ] Scroll Loading

## E2E Tests

- [ ] List should be scrollable and each item should be tappable
- [ ] Horizontal list should be scrollable and each item should be tappable

**Comment by manyaagarwal** [comment]
PR to close this: https://github.com/facebook/react-native/pull/29909
