### ISSUE TITLE
Propose a State Management Architecture

### ISSUE THREAD

**Issue by stealthanthrax** [MLH-Fellowship/react-native#137]
Propose a high level description/preview of the State Management Architecture.
- Tradeoffs of props vs context vs no state management
- A diagram of the dom tree and context

**Comment by chirag-singhal** [comment]
Proposed Architecture for State Management -  

![image](https://user-images.githubusercontent.com/42653703/86916455-400f4900-c141-11ea-90ba-d3e7ae066426.png)

**Comment by chirag-singhal** [comment]
@AnshG714 @manyaagarwal @anku255 @YashKumarVerma Any suggestions?
