### ISSUE TITLE
Implement the new Alert Screen

### ISSUE THREAD

**Issue by jevakallio** [MLH-Fellowship/react-native#15]
Contributes to #14

### Alert with one button
- [x] Show an alert with the message - "External USB drive detected!"  with a neutral button `Okay`.

### Alert with two buttons
 [ ] Show an alert with the message - "Your subscription has expired!" with a positive button `Renew` and a negative button `Ignore`

### Alert with three buttons 

- [x] Show an alert with the message - "Do you want to save your changes?" with a positive button `Yes`, a negative button `No` and a neutral button `Cancel`.

### Alert with more than three buttons [Only available on iOS] 

- [x] Can't think of any real-world use case. Could just show `Button One`, `Button Two`, `Button Three`, and so on.

## e2e tests

Write detox tests for each of the above alerts and test the following - 
- [x] Alert is visible
- [x] Alert can be dismissed by pressing any one of the buttons
- [x] Callback handler is called appropriately

## Suggestions
 - Style prop (Cancellable or not)
 - Android alerts dismissible by tap outside alert window

**Comment by anku255** [comment]
closed via #132
