### ISSUE TITLE
Remove the sidebar/drawer from Android.

### ISSUE THREAD

**Issue by anku255** [MLH-Fellowship/react-native#170]
In the new design, the hamburger icon has been removed but the navigation drawer is still there and can be accessed by swiping from the left. This needs to be removed. 

<img width="317" src="https://user-images.githubusercontent.com/22813027/88508152-afb77c00-cffb-11ea-9bdd-0abc5a687977.png" />

**Comment by manyaagarwal** [comment]
Implemented in final redesign
