### ISSUE TITLE
Write e2e tests for Switch

### ISSUE THREAD

**Issue by AnshG714** [MLH-Fellowship/react-native#6]
## Description
Add e2e tests for the Switch component for the RNTester app.
## Expected Results
A working test bench for testing the functionality of the switch component

## Snack, code example, screenshot, or link to a repository:
![Simulator Screen Shot - iPhone X - 2020-06-11 at 10 30 23](https://user-images.githubusercontent.com/29821563/84351288-b2d7e380-abd8-11ea-8f51-654a348e0385.png)

**Comment by anku255** [comment]
@AnshG714 Hold on before writing tests for `Switch` component. It was written before but had to be removed because it was flaky and used to fail on CI. 

See this - https://github.com/facebook/react-native/pull/23753
