### ISSUE TITLE
Implement new TextInput Screen

### ISSUE THREAD

**Issue by manyaagarwal** [MLH-Fellowship/react-native#91]
### TextInput with autoFocus={true}
Enter  username: 

### TextInput with maxLength={limit} 
Enter file name (limit 54):

### TextInput that does not allow spaces 
Enter email: 

### TextInput that replaces spaces with underscore '_' 
Enter file name: 

### TextInput along with "Clear" button
Enter username: 

### TextInput with  clearButtonMode={true} (`iOS` only) 
Enter username:

### TextInput with different autocaptialise settings 
- #### autocapitalise={characters} 
- #### autocapitalise={words} 
- #### autocapitalise={sentences}  

### TextInput with autocorrect={true} 
Search : 

### TextInput with clearTextOnFocus={true} (`iOS` only) 
Enter password: 

### TextInput with editable={false} 
username: [already existing value]

### TextInput with enablesReturnKeyAutomatically={true} (`iOS` only)
Send new message: 

### TextInput with inlineImageLeft
- Search Box without `inlineImagePadding` 
- Search Box with `inlineImagePadding={5}`

### TextInput with different keyboardAppearance
- default 
- light 
- dark 

### TextInput with multiline={true}
Enter short bio: 
- numberOfLines={10} 
- numberOfLines={10} and scrollEnabled={false} 

### TextInput with placeholder={string} 
- without placeholderTextColor
- with placeholderTextColor={color} 

### TextInput with returnKeyLabel={string} ( `android` only) 
Send Message: 

### TextInput with different returnKeyType for `crossPlatform`
- done 
- go 
- next 
- search 
- send 

### TextInput with different returnKeyType for `iOS`
- default 
- emergency-call 
- google
- join 
- route
- yahoo

### TextInput with different returnKeyType for `android` 
- none
- previous

### TextInput with secureTextEntry={true} 
Password: 

### TextInput with different textAlign values 
- left -> Username: 
- center -> Title: 
- right -> Amount:

### TextInput with selection={start,end} 
The start and end of the text input's selection. Set start and end to the same value to position the cursor.

### TextInput with selectionColor={yellow} 
Warning message: 

### TextInput with showSoftInputOnFocus={false} (`android` only) 
description: When false, it will prevent the soft keyboard from showing when the field is focused. The default value is true.

### TextInput with spellCheck={true} (`iOS` only) 
Enter Description : 

### TextInput with different values of textContentType (`iOS` only) 
values : 'none', 'URL', 'addressCity', 'addressCityAndState', 'addressState', 'countryName', 'creditCardNumber', 'emailAddress', 'familyName', 'fullStreetAddress', 'givenName', 'jobTitle', 'location', 'middleName', 'name', 'namePrefix', 'nameSuffix', 'nickname', 'organizationName', 'postalCode', 'streetAddressLine1', 'streetAddressLine2', 'sublocality', 'telephoneNumber', 'username', 'password' 

### TextInput with textContentType='newPassword' and passwordRules  (`iOS` only) 
Rule = "required: lower; required: upper; required: digit; required: [-]; minlength: 20;"
Choose new password: 

### TextInput with different textBreakStrategy values (`android` only) 
description: needed 
 - simple 
 - highQuality 
 - balanced 

### TextInput with different autoCompleteType values (`android` only)
- username
- password
- email
- name
- tel
- street-address
- postal-code
- cc-number
- cc-csc
- cc-exp
- cc-exp-month
- cc-exp-year

### TextInput with dataDetectorTypes={all} with multiline={true} and editable={false} (`iOS` only) 
description: Possible values for dataDetectorTypes are: 'phoneNumber', 'link' , 'address', 'calendarEvent', 'none', 'all'

## e2e Tests 

- [x] TextInput should accept input 
- [x] Input length should not exceed maximum length
- [x] No-spaces-Input should not allow spaces
- [x] TextInput should be cleared by tapping 'Clear' button

**Comment by stealthanthrax** [comment]
@manyaagarwal , this looks good to me 🚀

**Comment by YashKumarVerma** [comment]
:green_circle:  from my side
